name: Publish Docker

on:
  push:
    branches:
      - master

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 登录到腾讯云容器镜像仓库 (TCR)
      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.TCR_USERNAME }}  # 从 Secrets 获取 TCR 用户名
          password: ${{ secrets.TCR_PASSWORD }}  # 从 Secrets 获取 TCR 密码
          registry: ccr.ccs.tencentyun.com  # 腾讯云 TCR 登录地址
          
      # 构建并推送 Docker 镜像到 TCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # 使用新版的 Action
        with:
          context: .
          push: true
          tags: ccr.ccs.tencent.com/chenaimin/excalidraw-room:latest  # 替换为 TCR 仓库路径
          tag_with_ref: true
          tag_with_sha: true


      # 登出 TCR
      - name: Logout from Tencent Cloud TCR
        run: docker logout ccr.ccs.tencentyun.com  # 推送完成后登出
