name: Publish Docker

on:
  push:
    branches:
      - master

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 登录到腾讯云容器镜像仓库 (TCR)
      - name: Log in to Tencent Cloud TCR
        run: |
          echo ${TCR_PASSWORD} | docker login ${TCR_REGISTRY_URL} -u ${TCR_USERNAME} --password-stdin
        env:
          TCR_USERNAME: ${{ secrets.TCR_USERNAME }}  # 从 Secrets 获取 TCR 用户名
          TCR_PASSWORD: ${{ secrets.TCR_PASSWORD }}  # 从 Secrets 获取 TCR 密码
          TCR_REGISTRY_URL: ccr.ccs.tencentyun.com   # 腾讯云 TCR 的登录地址
          
      # 构建并推送 Docker 镜像到 TCR
      - name: Build and push Docker image
        run: |
          docker build -t ${TCR_REGISTRY_URL}/chenaimin/excalidraw-room:latest .
          docker push ${TCR_REGISTRY_URL}/chenaimin/excalidraw-room:latest
        env:
          TCR_REGISTRY_URL: ccr.ccs.tencentyun.com  # 腾讯云 TCR 的登录地址


      # 登出 TCR
      - name: Logout from Tencent Cloud TCR
        run: docker logout ccr.ccs.tencentyun.com  # 推送完成后登出
