name: Publish Docker

on:
  push:
    branches:
      - master

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: excalidraw/excalidraw-room
          tag_with_ref: true
          tag_with_sha: true
